// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

option go_package = "github.com/touchvas/fixture-service/app/grpc/fixture";

package protobuf;

// The Fixture service definition.
service Fixture {
  // Sends GetOdds status request
  rpc GetFixture (GetFixtureRequest) returns (GetFixtureReply) {}
  rpc GetSMSGames(RequestSMSGame) returns (SMSGamesResponse) {}
  rpc Ping (PingRequest) returns (PongRequest) {}
  rpc GetTournamentID (TournamentIDRequest) returns (TournamentIDReply) {}

}

message PingRequest {

}

message PongRequest {
  int64 Status = 1;
  string Data = 2;
}

message GetMatchStatusRequest {
  int64 matchID = 1;

}

message GetMatchStatusReply {


}

message GetFixtureRequest {
  int32 matchID = 1;
}

// The response message containing the odds status
message GetFixtureReply {
  int64 matchId = 1;
  string matchName = 2;
  string tournament = 3;
  string categoryName = 4;
  string sportName = 5;
  string matchStatus = 6;
  string homeScore = 7;
  string awayScore = 8;
  int64 status = 9;
  string date = 10;
  int64 gameID = 11;
  int64 sportID = 12; // this
  int64 tournamentID = 13; // this
  int64 GSSportID = 14; // this
  int64 HomeCompetitorId  =15;
    int64 AwayCompetitorId =16;
}

message SMSGamesResponse {

  repeated SMSGame games = 1;

}

message SMSGame  {
  string  Name = 1;
  int64  GameID = 2;
  float Home = 3;
  float Draw = 4;
  float Away = 5;
  string Date = 6;
  int64 Priority = 7;
  int64 MatchID = 8;
  string Specifier = 9;
  string HomeOutcomeID =10;
string AwayOutcomeId = 11;
string DrawOutcomeID =12;
}

message RequestSMSGame  {

  int64 Count = 1;
  int64 FromPriority = 2;

}

message TournamentIDRequest {
  int64 matchID = 1;
}

message TournamentIDReply {
  int64 tournamentID = 1;
}
